### ISSUE TITLE
Choice of 100 ohm resistor for crystal oscillator

### ISSUE THREAD

**Issue by DLehenbauer** [diva-eng/diva-card#1]
I was wondering how you chose the value of 100 ohms for the resistor (R10)?

I am working on a design using the same parts (RP2040 and X322512MSB4SI oscillator).  However, I kept the 1K resistor from the reference design.

My prototype works but requires a firmware workaround to increase the startup delay to 16ms or more.
```cmake
# On tested sample, 8ms was intermittent and 16ms was reliable.
# 64ms provides a large tolerance.
add_compile_definitions(PICO_XOSC_STARTUP_DELAY_MULTIPLIER=64)
```
I thought maybe you ran into the same issue and reduced the value of R10 to compensate?

**Comment by r1cebank** [comment]
The reference design was using a different capacitor I recall and since we chose a different oscillator the feed resistor has also been adjusted to that oscillator. I do not recall what was the actual calculation done but it was based on the oscillator ESR https://www.lcsc.com/datasheet/lcsc_datasheet_2403291504_YXC-Crystal-Oscillators-X322512MSB4SI_C9002.pdf and existing designs using the same part. Hope this helps

**Comment by DLehenbauer** [comment]
I appreciate the response.  Sounds like you got it right on the first try.  Thanks!
